version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - platformio-v1-{{ .Branch }}-{{ checksum "platformio.ini" }}
            - platformio-v1-{{ .Branch }}-
            - platformio-v1-
      - run:
          name: Set up
          command: |
            pip install -U platformio
            pio update
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/venv  # this path depends on where pipenv creates a virtualenv
          key: platformio-v1-{{ .Branch }}-{{ checksum "platformio.ini" }}
      - run:
          name: Build
          command: |
            pio run -e uva_solar_car
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Test
          command: |
            pio test -e native
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        